---
title: make notify
output: blastula::blastula_email
--- 

```{r,echo=FALSE, message=FALSE}
library(jsonlite); library(purrr); library(dplyr); library(kableExtra)

commit <- readLines(here::here("logs/commit.txt"))
exit_code_path <- here::here("logs/exit-code.txt")
exit_code <- readLines(exit_code_path) |> as.numeric()
sucess <- ifelse(exit_code == 0, TRUE, FALSE)

validation_report <- function(resource) {
  
  name <- pluck(resource, "name")
  valid <- pluck(resource, "validation", "valid")
  stats <- pluck(resource, "validation", "tasks", 1, "resource", "stats")
  stats["size"] <- R.utils::hsize(pluck(stats, "bytes"))
  
  result <- c(list(name = name), stats[c("size")] , list(valid = valid), stats[c("fields", "rows")])
  
  data.frame(result)
}

dp <- read_json(here::here("datapackage.json"))

df <- map_df(dp$resources, validation_report) |> arrange(valid)
```

O fluxo ETL de atualização do projeto age7 foi concluído com `r ifelse(sucess == TRUE, "SUCESSO", "__FRACASSO__")` em `r file.mtime(exit_code_path)`.

Os logs da execução estão disponíveis `r ifelse(sucess == TRUE, glue::glue("no commit [{commit}](https://github.com/transparencia-mg/age7/commit/{commit})"), "no servidor")`.

Dos `r length(dp$resources)` recursos, `r length(dp$resources) - sum(df$valid)` tiveram erros de validação.

```{r,echo=FALSE}
df |> 
  kbl() |> 
  kable_minimal() |> 
  column_spec(3, color = ifelse(df$valid == FALSE, "red", "green"))
```

Att.
